language: python
cache: pip
branches:
  only:
    - master
    - 2to3
python:
  - 3.6
install:
  # get pipenv to install dependencies
  - pip install pipenv

  # run through install as written in docs
  - pipenv install --dev --skip-lock
  - pipenv run pip install git+https://github.com/labjack/LabJackPython.git

  # install ffmpeg
  # install avbin

before_script:
  # setup virtual frame buffer (i.e. headless display)
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  # run tests
  - pipenv run py.test tests --cov pyStim
  # build documentation
  - cd docs
  - pipenv run sphinx-build -b html source build/html
  # sphinx-build -W -b html source build/html  # warnings as errors
  # sphinx-build -W -b pdf source build/pdf

after_success:
  # push coverage results
  - pipenv run coveralls

deploy:
  # push html documentation to github pages
  provider: pages
  skip_cleanup: true
  github_token: $travis_sphinx_ghpages
  local_dir: docs/build/html
  on:
    branch: master
