name: sp_env
channels:
- conda-forge
- anaconda
- defaults
dependencies:
- python=2.7.13
- numpy
- scipy
- Pillow
- matplotlib
- pandas
- pyopengl
- lxml
- openpyxl
- configobj
- sortedcontainers
- pip:
  - psychopy
  - igor
  - labjackpython
  - moviepy
  - pycrafter4500
  - pyusb
  - tabulate
  - tqdm

